name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.5.2
  - pip=22.3.1
  - scikit-learn=1.1.3
  - matplotlib=3.6.2
  - plotly==5.11.0
  - pillow=9.2.0
  - mlflow=2.0.1
  - pip:
      - wandb==0.13.5
      - omegaconf==2.2.3
