name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.28.1
  - pip=22.3.1
  - mlflow=2.0.1
  - hydra-core=1.2.0
  - pip:
      - wandb==0.13.5
      - hydra-joblib-launcher==1.2.0
